-- ==============================================================================
-- SEED — Carga inicial de clientes (LançaQi)
-- ------------------------------------------------------------------------------
-- Rodar no SQL Editor do Supabase APÓS a Migracao_002 (tabela `clientes`).
-- Idempotente: só insere nomes que ainda não existem (pode rodar várias vezes
-- sem duplicar). Apenas `nome` é preenchido; endereco/cnpj/telefone ficam NULL.
-- ==============================================================================

INSERT INTO public.clientes (nome)
SELECT v.nome
FROM (VALUES
    ('Hype Tecnologia'),
    ('Catta Preta'),
    ('Quadoo'),
    ('Lt Energia'),
    ('Acerbi Campagnaro'),
    ('Lan Construtora'),
    ('Sito Arquitetura'),
    ('Jose Olimpio'),
    ('Studio Universalis'),
    ('Flowval'),
    ('Cms Assessoria'),
    ('Fato Engenharia'),
    ('Souza e Pedras'),
    ('Carleto Parafusos'),
    ('Montal'),
    ('Ebolsas'),
    ('Eletron Telecom'),
    ('Leonardo Bandeira'),
    ('Alcoe Advogados'),
    ('Belli Advocacia'),
    ('Instituto Homa'),
    ('Transfernandes'),
    ('Almeida Lopes'),
    ('Hd Vitoria'),
    ('Zuriel'),
    ('Abgi'),
    ('Clinica Dianthus'),
    ('Breedom Cervejaria'),
    ('Mvprec'),
    ('Prisma Automotiva'),
    ('Ctmig'),
    ('Plaft'),
    ('Nau Capital'),
    ('Lucas Miranda'),
    ('Mastersound'),
    ('Tempuz'),
    ('Kalenborn'),
    ('Dmt Palestras'),
    ('Veneto'),
    ('Godinho Barbosa'),
    ('Assoceg'),
    ('Infoco Seguros'),
    ('A Clinic'),
    ('Bernardo Franco'),
    ('Transodilon'),
    ('Plus Participacoes'),
    ('Weldtronic'),
    ('Grimaldi e Rodrigues'),
    ('Lm Mining'),
    ('Ferreira e Goncalves'),
    ('Repol'),
    ('Magriotis'),
    ('Par Advogados'),
    ('Minipa'),
    ('Diogo Pimenta'),
    ('Clinica Duo'),
    ('Multiseg'),
    ('Grupo Multipar'),
    ('Mesara'),
    ('C2T Advogados'),
    ('Franqueira Seguros'),
    ('Fqma Advogados'),
    ('Biosut'),
    ('Roesel Transportes'),
    ('Grupo Prestarh'),
    ('Cdm Assessoria'),
    ('New Human'),
    ('Depyl Action'),
    ('Marpress'),
    ('Construtora Brick'),
    ('Cartorio Caete'),
    ('Hype'),
    ('Leroy Associados'),
    ('Mg Car'),
    ('Vener'),
    ('Fabio Lopes'),
    ('Bruno Vargas'),
    ('Rubtek'),
    ('Roesel Advogados'),
    ('Okay Coworking'),
    ('Outsmart'),
    ('Condorlog'),
    ('Monte Siao'),
    ('LG Conceito'),
    ('Clinica Laversa'),
    ('Castro e Chagas Advogados')
) AS v(nome)
WHERE NOT EXISTS (
    SELECT 1 FROM public.clientes c WHERE c.nome = v.nome
);
